$pathVBox="\"C:/Program Files/Oracle/VirtualBox/VboxManage.exe\""
$pathApplication = File.expand_path("../../../Robogroft", __FILE__)
$pathPub = "#{$pathApplication}/public"
$pathFile = "#{$pathPub}/Files"
$pathScript = "#{$pathPub}/Script"
$pathVhd = "D:/Vhd"
$pathMount = "D:/mount"
$pathResult = "#{$pathPub}/Result"
$pathHttp = "http://localhost"
$pathHttpRobogroft = "http://localhost:3000"
$filesize = 32