$pathVBox="\"C:/Program Files/Oracle/VirtualBox/VboxManage.exe\""
$pathApplication = File.expand_path("../../../Robogroft", __FILE__)
$pathPub = "#{$pathApplication}/public"
$pathLock = "#{$pathPub}/Locker.txt"
$pathLockZip = "#{$pathPub}/Lockerzip.txt"
$pathVhd = "D:\\server\\Vhd"
$pathVhd2 = "D://server//Vhd"
$pathVhdFolder2 = "D:/server/Mounting"
$pathVhdFolder = "D:\\server\\Mounting"
$pathBackup = "D:\\server\\Backup"
$pathToVms = "D:\\server\\NoAddons"
$pathFile = "#{$pathPub}/Files"
$pathApp = "#{$pathApplication}/app"
$pathResult = "#{$pathPub}/Result"
$pathResult2 = "#{$pathPub2}\\Result"
$pathTask = "#{$pathPub}/Tasks"
$pathCurrentTask = "#{$pathPub}/Current"
$pathComputers = "D:/public"
$pathHttp = "http://localhost"
$pathHttpRobogroft = "http://localhost:3000"
$filesize = 32
$limit_vms = 1
$timeout = 200